name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "Hello World"
      - run: exit 1
      - run: echo "Hello World2"
        if: ${{ failure() }}
