name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "Hello World"
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_INTEGER: ${{123}}
          LITERAL_STRING: HELLO
          LITERAL_BOOL: ${{true}}
          TEST: test
