name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "Hello World"
      - id: source
        run: echo "result=hello" >> "${ GITHUB_OUTPUT }"
      - run: echo ${ steps.source.output.result }
      - run: echo "RESULT=hello" >> "${ GITHUB_ENV }"
      - run: echo "${ RESULT }"
