name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "Hello World"
      - id: source
        run: echo "result=hello" >> "${GITHUB_OUTPUT}"
      - run: echo "${RESULT}"
        env:
          RESULT: ${{steps.source.outputs.result}}
      - run: echo "RESULT=hello2" >> "${GITHUB_ENV}"
      - run: echo "${RESULT}"
