name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "Hello World"
      - run: echo "${ACTOR}"
      - run: echo "#{vars.VARKEY}"
      - run: echo "#{secrets.SECRETKEY}"
