name: Practice
on: push
jobs:
  print_branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO=world" >> ${GITHUB_OUTPUT}
        id: print
      - run: echo "${{steps.print.outputs.HELLO}}"
