name: Practice
on: push
jobs:
  print_branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CURRENT_BRANCH}"
        env:
          CURRENT_BRANCH: ${{github.ref}}
        if: ${{ github.actor == "tatsumi-test" }}
