name: Practice
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: staging
        required: false
        description: Environment
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # minitest:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.3.0'
  #         bundler-cache: true
  #     - run: ruby hello.rb
  #       name: minitest
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - name: print USERNAME
        run: echo "${USERNAME}"
      - name: print PASSWORD
        run: echo "${PASSWORD}"
